name: Terraform

on:
  push:
    branches:
      - main  # or the name of your default branch

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    - name: Upgrade Azure CLI
      run: az upgrade --yes

    - name: Check Azure CLI Version
      run: az --version

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0  # Update this to your desired Terraform version

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        allow-no-subscriptions: true

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

    # Uncomment the following step for Terraform Apply
    # - name: Terraform Apply
    #   run: terraform apply -auto-approve
